# Form implementation generated from reading ui file 'savingAccount.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_checkingAccount(object):
    def setupUi(self, checkingAccount):
        checkingAccount.setObjectName("checkingAccount")
        checkingAccount.resize(375, 450)
        self.centralwidget = QtWidgets.QWidget(parent=checkingAccount)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_nameLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_nameLabel.setGeometry(QtCore.QRect(110, 20, 161, 41))
        self.welcome_nameLabel.setObjectName("welcome_nameLabel")
        self.balance_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.balance_Label.setGeometry(QtCore.QRect(50, 70, 281, 41))
        self.balance_Label.setObjectName("balance_Label")
        self.last_editLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.last_editLabel.setGeometry(QtCore.QRect(90, 110, 191, 20))
        self.last_editLabel.setObjectName("last_editLabel")
        self.action_requestLabel = QtWidgets.QLabel(parent=self.centralwidget)
        self.action_requestLabel.setGeometry(QtCore.QRect(50, 160, 271, 20))
        self.action_requestLabel.setObjectName("action_requestLabel")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(105, 220, 181, 20))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(105, 280, 181, 20))
        self.pushButton_2.setObjectName("pushButton_2")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(190, 190, 113, 20))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(90, 190, 101, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(90, 250, 91, 20))
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(190, 250, 113, 20))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton_3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(95, 320, 201, 20))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(40, 360, 111, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(240, 360, 101, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        checkingAccount.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=checkingAccount)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 375, 18))
        self.menubar.setObjectName("menubar")
        checkingAccount.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=checkingAccount)
        self.statusbar.setObjectName("statusbar")
        checkingAccount.setStatusBar(self.statusbar)

        self.retranslateUi(checkingAccount)
        QtCore.QMetaObject.connectSlotsByName(checkingAccount)

    def retranslateUi(self, checkingAccount):
        _translate = QtCore.QCoreApplication.translate
        checkingAccount.setWindowTitle(_translate("checkingAccount", "MainWindow"))
        self.welcome_nameLabel.setText(_translate("checkingAccount", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Welcome, Placeholder</span></p></body></html>"))
        self.balance_Label.setText(_translate("checkingAccount", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">Your </span><span style=\" font-size:12pt; font-weight:600;\">savings</span><span style=\" font-size:12pt;\"> account balance is: </span></p></body></html>"))
        self.last_editLabel.setText(_translate("checkingAccount", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Last access: X/XX/XX</span></p></body></html>"))
        self.action_requestLabel.setText(_translate("checkingAccount", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt;\">What would you like to do?</span></p></body></html>"))
        self.pushButton.setText(_translate("checkingAccount", "Deposit"))
        self.pushButton_2.setText(_translate("checkingAccount", "Withdrawal"))
        self.label.setText(_translate("checkingAccount", "<html><head/><body><p><span style=\" font-size:10pt;\">Deposit Amount:</span></p></body></html>"))
        self.label_2.setText(_translate("checkingAccount", "<html><head/><body><p><span style=\" font-size:10pt;\">Withdrawal Amount:</span></p></body></html>"))
        self.pushButton_3.setText(_translate("checkingAccount", "Savings Account Statement"))
        self.pushButton_4.setText(_translate("checkingAccount", "Checking Account"))
        self.pushButton_5.setText(_translate("checkingAccount", "Return to Login"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    checkingAccount = QtWidgets.QMainWindow()
    ui = Ui_checkingAccount()
    ui.setupUi(checkingAccount)
    checkingAccount.show()
    sys.exit(app.exec())
