# Form implementation generated from reading ui file 'welcomeWindow.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WelcomeWindow(object):
    def setupUi(self, WelcomeWindow):
        WelcomeWindow.setObjectName("WelcomeWindow")
        WelcomeWindow.setEnabled(True)
        WelcomeWindow.resize(375, 450)
        WelcomeWindow.setStyleSheet("background-color: rgb(126, 132, 107);")
        self.centralwidget = QtWidgets.QWidget(parent=WelcomeWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.welcome_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.welcome_Label.setGeometry(QtCore.QRect(100, 20, 161, 111))
        self.welcome_Label.setObjectName("welcome_Label")
        self.login_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_Label.setGeometry(QtCore.QRect(20, 140, 331, 20))
        self.login_Label.setObjectName("login_Label")
        self.name_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_Label.setGeometry(QtCore.QRect(90, 180, 51, 21))
        self.name_Label.setObjectName("name_Label")
        self.PIN_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.PIN_Label.setGeometry(QtCore.QRect(90, 220, 61, 21))
        self.PIN_Label.setObjectName("PIN_Label")
        self.register_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.register_Label.setGeometry(QtCore.QRect(30, 350, 311, 21))
        self.register_Label.setObjectName("register_Label")
        self.login_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(140, 300, 81, 21))
        self.login_button.setStyleSheet("background-color: rgb(89, 78, 54);")
        self.login_button.setObjectName("login_button")
        self.name_Edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_Edit.setGeometry(QtCore.QRect(160, 180, 113, 20))
        self.name_Edit.setStyleSheet("background-color: rgb(208, 221, 215);")
        self.name_Edit.setObjectName("name_Edit")
        self.PIN_Edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.PIN_Edit.setGeometry(QtCore.QRect(160, 220, 113, 20))
        self.PIN_Edit.setStyleSheet("background-color: rgb(208, 221, 215);")
        self.PIN_Edit.setObjectName("PIN_Edit")
        self.accountType_Label = QtWidgets.QLabel(parent=self.centralwidget)
        self.accountType_Label.setGeometry(QtCore.QRect(60, 250, 101, 41))
        self.accountType_Label.setObjectName("accountType_Label")
        self.checking_Radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.checking_Radio.setGeometry(QtCore.QRect(170, 260, 71, 21))
        self.checking_Radio.setObjectName("checking_Radio")
        self.account_radio_group = QtWidgets.QButtonGroup(WelcomeWindow)
        self.account_radio_group.setObjectName("account_radio_group")
        self.account_radio_group.addButton(self.checking_Radio)
        self.savings_Radio = QtWidgets.QRadioButton(parent=self.centralwidget)
        self.savings_Radio.setGeometry(QtCore.QRect(250, 260, 81, 21))
        self.savings_Radio.setObjectName("savings_Radio")
        self.account_radio_group.addButton(self.savings_Radio)
        self.register_button = QtWidgets.QPushButton(parent=self.centralwidget)
        self.register_button.setGeometry(QtCore.QRect(140, 390, 81, 21))
        self.register_button.setStyleSheet("background-color: rgb(89, 78, 54);")
        self.register_button.setObjectName("register_button")
        self.login_error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.login_error_label.setGeometry(QtCore.QRect(120, 330, 231, 20))
        self.login_error_label.setObjectName("login_error_label")
        self.register_error_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.register_error_label.setGeometry(QtCore.QRect(120, 420, 191, 16))
        self.register_error_label.setObjectName("register_error_label")
        self.account_selection_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.account_selection_label.setGeometry(QtCore.QRect(120, 280, 171, 20))
        self.account_selection_label.setText("")
        self.account_selection_label.setObjectName("account_selection_label")
        WelcomeWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(WelcomeWindow)
        QtCore.QMetaObject.connectSlotsByName(WelcomeWindow)

    def retranslateUi(self, WelcomeWindow):
        _translate = QtCore.QCoreApplication.translate
        WelcomeWindow.setWindowTitle(_translate("WelcomeWindow", "MainWindow"))
        self.welcome_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt;\">Welcome</span></p><p align=\"center\"><span style=\" font-size:14pt;\">to</span></p><p align=\"center\"><span style=\" font-size:14pt;\">World\'s Best Bank</span></p><p align=\"center\"><br/></p></body></html>"))
        self.login_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Login with your name and four digit PIN</span></p></body></html>"))
        self.name_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Name:</span></p></body></html>"))
        self.PIN_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">PIN:</span></p></body></html>"))
        self.register_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:12pt; font-weight:600; text-decoration: underline;\">Or, Register To Create an Account</span></p></body></html>"))
        self.login_button.setText(_translate("WelcomeWindow", "Login"))
        self.accountType_Label.setText(_translate("WelcomeWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">Account Type:</span></p></body></html>"))
        self.checking_Radio.setText(_translate("WelcomeWindow", "Checking"))
        self.savings_Radio.setText(_translate("WelcomeWindow", "Savings"))
        self.register_button.setText(_translate("WelcomeWindow", "Register"))
        self.login_error_label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))
        self.register_error_label.setText(_translate("WelcomeWindow", "<html><head/><body><p align=\"center\"><br/></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    WelcomeWindow = QtWidgets.QMainWindow()
    ui = Ui_WelcomeWindow()
    ui.setupUi(WelcomeWindow)
    WelcomeWindow.show()
    sys.exit(app.exec())
